### ISSUE TITLE
Cannot call yaml_parse_file

### ISSUE THREAD

**Issue by drkpkg** [highlands-framework/highlands-framework#3]
The logs send me this: 

[Sun Nov 22 21:11:57 2015] PHP Fatal error:  Call to undefined function yaml_parse_file() in /home/drkpkg/Proyectos/highlands-framework/core/Core.php on line 21

The yaml file didn't show in the test server.

**Comment by lanstat** [comment]
verificaste que tienes instalado yaml?

**Comment by drkpkg** [comment]
Justamente era eso, habria que ponerlo como dependencia(?)

**Comment by isjing** [comment]
Yep, creo que seria lo mejor.
